### ISSUE TITLE
Error: Render is not a function

### ISSUE THREAD

**Issue by stephenrichard** [moritzlaube/parcel-transformer-html-datasrc#1]
Hello, I tried to install this package to handle lazyloading with [vanilla-lazyload](https://www.andreaverlicchi.eu/vanilla-lazyload/).
I followed the steps exactly as instructed on the README (`npm i -D parcel-transformer-html-datasrc` and creating a .parcelrc file next to package.json) but I get the following error and I'm not sure how to proceed : 

![Capture d’écran 2021-11-08 à 09 14 12](https://user-images.githubusercontent.com/4067686/140711933-da84c529-d896-4e5e-817a-0fd695d1874d.png)

Is there anything I am missing during the installation or a dependency colliding ?

Here are my dependencies :
```
"parcel" : "^2.0.0",
"parcel-transformer-html-datasrc" : "^1.1.5",
"@parcel/transformer-sass": "^2.0.0",
"posthtml-include": "^1.7.2",
```
And my `.parcelrc` frile : 
```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.html": [
      "parcel-transformer-html-datasrc"
    ]
  }
}
```

**Comment by moritzlaube** [comment]
@stephenrichard: You can now install version 1.1.6 which solves your issue. @mischnic: Thanks again for you quick help.
