### ISSUE TITLE
When executing the instruction given here, a strange error appears or resources (css, js) are not loaded 

### ISSUE THREAD

**Issue by haosmos** [moritzlaube/parcel-transformer-html-datasrc#6]
Hi! 

I trying to settings your plugin for lazy-loading image via replace low-resolution image high-resolution image after trigger some event.  

I was following you instruction: 

1. download plugin

2. create .parcelrc: 

{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.html": ["parcel-transformer-html-datasrc"]
  }
}

3. create .html-datasrc.config.json: 

{
  "img": ["data-src", "data-bp"],
  "div": ["data-background-image"]
}

but, i got error: 

![webstorm64_8jNzjDEw7X](https://user-images.githubusercontent.com/30666874/144482068-ca3018c4-7d6a-4aaa-aa70-a32929fbced5.png)

but, when i delete "..." in the .parcelrc this error disapire:

![webstorm64_m5tSknxyBQ](https://user-images.githubusercontent.com/30666874/144482403-d00e7062-13c5-4117-a440-25f02151dcb3.png)

and the build seems to work... But it doesn't really work:  

![chrome_HBU9AZt2RP](https://user-images.githubusercontent.com/30666874/144483443-4c819d8a-f199-42fb-a69d-594a25c6b87c.png)

Interestingly, when I delete .parcelrc and .html-datasrc.config.json files — the build works as expected (without lazy-loading image, off course): 

![n4YybQWJYO](https://user-images.githubusercontent.com/30666874/144484043-58bcc582-621a-4a51-9b50-b98ce8f99e06.png)

so, how to configure out the plugin settings or there i did mistake?

here my repo: https://github.com/haosmos/bankist

**Comment by moritzlaube** [comment]
Hey! Thanks for reaching out. First of all: You need to add the `"..."` in the `.parcelrc` file since that is how parcel then adds the default resolvers on top of `parcel-transformer-html-datasrc`. I'm assuming this is also the reason why parcel isn't bundling your js and scss when you delete the dots … 

It seems to me that the build error has nothing to do with the plugin per se. Maybe your image conversion with sharp gets in the way? But it's hard to see at a first glance. I can have a closer look tomorrow to see where your code is breaking.

P.S.: you misspelled your html nano config file. It is `.htmlnanorc.json`. But it is not fixing the bug. just letting you know.

**Comment by moritzlaube** [comment]
Oh and one more thing: You only use `data-src`. So you technically don't have to use the `.html-datasrc.config.json` since this is supported out of the box.

**Comment by mischnic** [comment]
One reason you could get `Failed to resolve '..some hash..' from './src/main.html'` is when this transformer replaces something with the result of `addURLDependency` which is also already handled by Parcel's HTML transformer.

For example I would expect that error with
```json
{
  "img": ["src"]
}
```
Not sure if this could be the case here @moritzlaube ?

**Comment by moritzlaube** [comment]
I’ll check!

**Comment by haosmos** [comment]
> Hey! Thanks for reaching out. First of all: You need to add the `"..."` in the `.parcelrc` file since that is how parcel then adds the default resolvers on top of `parcel-transformer-html-datasrc`. I'm assuming this is also the reason why parcel isn't bundling your js and scss when you delete the dots … 
> 
> It seems to me that the build error has nothing to do with the plugin per se. Maybe your image conversion with sharp gets in the way? But it's hard to see at a first glance. I can have a closer look tomorrow to see where your code is breaking.
> 
> P.S.: you misspelled your html nano config file. It is `.htmlnanorc.json`. But it is not fixing the bug. just letting you know.

thanks for you answer! 

I deleted unnecessary config files (the files that may have somehow conflicted with the default parcel settings) and add "..." in the .parcelrc file. But the same error 😢

![webstorm64_hFYUIGVngk](https://user-images.githubusercontent.com/30666874/144522593-b6490d08-1ecc-4f5d-bff1-4a661ddf5bcd.png)

**Comment by moritzlaube** [comment]
I found the bug! Thanks for the hint @mischnic! There was a simple typo in the `parcel-transformer-html-datasrc` default config! @haosmos: Please update `parcel-transformer-html-datasrc` to the latest version (1.3.3) by typing `npm i parcel-transformer-html-datasrc`. That fixes your bug. Let me know if you have any further questions. Nice work by the way.

**Comment by haosmos** [comment]
> I found the bug! Thanks for the hint @mischnic! There was a simple typo in the `parcel-transformer-html-datasrc` default config! @haosmos: Please update `parcel-transformer-html-datasrc` to the latest version (1.3.3) by typing `npm i parcel-transformer-html-datasrc`. That fixes your bug. Let me know if you have any further questions. Nice work by the way.

it works! thank you so much! 

But... 

I use the intersection observer API to track when the user approaches the image. 

In case of using img tag, replacing low-resolution image with high-resolution image works fine: low-resolution image is replaced with high-resolution image whose path is stored in data-src: 

```
<img
	  src="./img/digital-lazy.jpg?as=webp"
	  data-src="./img/digital.jpg?as=webp"
	  alt="Computer"
	  class="features__img lazy-img"
/>
```

But, if I use the <picture> tag and put the data-src in the <source> tag, no magic happens: 

```
<picture>
        <source 
          srcset="./img/digital-lazy.jpg?as=webp"
          type="image/webp"
          data-src="./img/digital.jpg?as=webp"
        />

        <img
          src="./img/digital.jpg?as=webp"
          data-src="./img/digital.jpg"
          alt="Computer"
          class="features__img lazy-img"
        />
</picture>
```

here's the js code: 

```
// Lazy loading images
const imgTargets = document.querySelectorAll("source[data-src]");

const loadImg = function (entries, observer) {
  const [entry] = entries;

  if (!entry.isIntersecting) return;

  // Replace src with data-src
  entry.target.src = entry.target.dataset.src;

  entry.target.addEventListener("load", function () {
    entry.target.classList.remove("lazy-img");
  });

  observer.unobserve(entry.target);
};
```
![woCwkKIXsx](https://user-images.githubusercontent.com/30666874/144607574-4757e3b8-b994-4e3e-85ac-bb6bd0d7d7c3.png)

For some reason the path to the high-resolution image in the browser is displayed differently than the path to the other images: the path to the other images is displayed as a link, but in the case of using data-src in the <source> tag the path is simply displayed as text. 

I don't know, maybe the problem has something to do with the fact that I'm using parcel's built-in mechanism for converting images from .jpg to .webp... but in case of using <img> tag everything works fine...

**Comment by moritzlaube** [comment]
I didn't really dive into your code. But it seems that you aren't replacing the right attribute on the source tag. Meaning, you should replace the `srcset`-attribute on the `source`-tag with the `data-src-content. Not the `src`-attribute. The `source`-tag can't have a `src`-attribute when placed inside a `picture`-tag. Have a look on MDN.

**Comment by haosmos** [comment]
> I didn't really dive into your code. But it seems that you aren't replacing the right attribute on the source tag. Meaning, you should replace the `srcset`-attribute on the `source`-tag with the `data-src-content. Not the `src`-attribute. The `source`-tag can't have a `src`-attribute when placed inside a `picture`-tag. Have a look on MDN.

Thank you very much for the answer! 

Yes, now the question is how to select the right element and then replace it with what is stored in the data. 

As far as I understand, the high-resolution image should be stored in data-srcset, but where exactly? in the `picture` tag or in the `source`? 

Right now my layout looks like this: 

```
<picture>
	<source srcset="./img/digital-lazy.jpg?as=webp"
		type="image/webp"
		data-srcset="./img/digital.jpg?as=webp"
		alt="Computer"
		class="features__img lazy-img"
	/>
        
	<img
		src="./img/digital.jpg?as=webp"
		alt="Computer"
        class="features__img lazy-img"
	/>
</picture>
```

The js looks like this: 

I can't figure out which element I need to monitor and then replace `srcset `in it - `picture` or `source`

I tried it like this: 

```
const imgTargets = document.querySelectorAll("picture[data-srcset]"); 

// Replace srcset with data-srcset
entry.target.srcset = entry.target.dataset.srcset;
```
and so on: 
```
const imgTargets = document.querySelectorAll("source[data-srcset]");

// Replace srcset with data-srcset
entry.target.srcset = entry.target.dataset.srcset;
```

but it doesn't work...

![chrome_ykuOZutC7B](https://user-images.githubusercontent.com/30666874/144621452-50f23c83-31bd-45e1-9f82-405dcbaaba05.png)

**Comment by moritzlaube** [comment]
Hej! I haven't worked with the IntersectionObserver for a while. You probably need to check the value of entry.target ... But you can make your life much easier if you use one of the many libraries that support lazy loading images so you don't have to reinvent the wheel. That is what the plugin is actually made for. Try `https://apoorv.pro/lozad.js/`. It has a really easy api and should be perfect for your use case..

**Comment by haosmos** [comment]
> Hej! I haven't worked with the IntersectionObserver for a while. You probably need to check the value of entry.target ... But you can make your life much easier if you use one of the many libraries that support lazy loading images so you don't have to reinvent the wheel. That is what the plugin is actually made for. Try `https://apoorv.pro/lozad.js/`. It has a really easy api and should be perfect for your use case..

Thank you so much for answering my questions! 

Thanks for the recommendation of the library! i will try it. But also I really want to figure out how to solve my problem and implement lazy-load images using parsel itself and your wonderful plugin. 

I almost had the desired result: the low-resolution image is replaced by a high-resolution image when you scroll down to it. 
But! for some reason the "lazy-img" class, which applies the blur effect, is not removed: 

![46RMCnjl9A](https://user-images.githubusercontent.com/30666874/144662480-5fc1bd54-8ffc-42ba-a33c-5f6eadf25033.png)

entry.target is correct: 

![9EwqSmQ1rq](https://user-images.githubusercontent.com/30666874/144662502-e9f6df1b-b849-44f5-8833-d13b7273b6ad.png)

although I think this is hardly a problem of your wonderful plugin. 

One last question - do you have any idea why this class `lazy-img` is not being removed? 

In the case of using the `img` tag this class is removed, but in the case of using the `picture` tag, for some reason, it is not.

**Comment by moritzlaube** [comment]
Hi! Please have in mind: the picture (or source) element itself does not display anything; it merely provides a context for its contained img element that enables it to choose from multiple URLs.  That means, it is always the img element that will render the image that the user sees.

A normal usage would be like this:

```
<picture>
  <source srcset="img/city-m.jpg" media="(max-width: 960px)">
  <source srcset="img/city-l.jpg" media="(min-width: 961px)">
  <img class="some-class" src="img/city-l.jpg" alt="city"/>
</picture>
```

The lazy loading approach would look like this:

```
<picture class="lazy">
  <source data-srcset="img/river-m.jpg" media="(max-width: 960px)">
  <source data-srcset="img/river-l.jpg" media="(min-width: 961px)">
  <img data-srcset="img/river-l.jpg" alt="river"/>
</picture>
```

That means with JS you need to replace the data-srcset on the source element. The browser then takes this url and puts it into the img.src attribute. 

In your code you're querying the img tags like so:

`const imgTargets = document.querySelectorAll("img[data-src]");``

But you should try to get the source tags like so `const sourceTags = document.querySelectorAll(".lazy > source") and then attach the IntersectionObserver to this NodeList. 

Have in mind that you should replace the img.src with the url in the data-src for browsers who don't support the IntersectionObserver with a simple check:

```
if (intersectionObserver in window) {
...
} else {
// replace img.src with data-src from img-tag or data-srcset from source-tag
}
```
Hope, that helps.

Have a nice weekend. 

M

**Comment by haosmos** [comment]
> Hi! Please have in mind: the picture (or source) element itself does not display anything; it merely provides a context for its contained img element that enables it to choose from multiple URLs. That means, it is always the img element that will render the image that the user sees.
> 
> A normal usage would be like this:
> 
> ```
> <picture>
>   <source srcset="img/city-m.jpg" media="(max-width: 960px)">
>   <source srcset="img/city-l.jpg" media="(min-width: 961px)">
>   <img class="some-class" src="img/city-l.jpg" alt="city"/>
> </picture>
> ```
> 
> The lazy loading approach would look like this:
> 
> ```
> <picture class="lazy">
>   <source data-srcset="img/river-m.jpg" media="(max-width: 960px)">
>   <source data-srcset="img/river-l.jpg" media="(min-width: 961px)">
>   <img data-srcset="img/river-l.jpg" alt="river"/>
> </picture>
> ```
> 
> That means with JS you need to replace the data-srcset on the source element. The browser then takes this url and puts it into the img.src attribute.
> 
> In your code you're querying the img tags like so:
> 
> `const imgTargets = document.querySelectorAll("img[data-src]");``
> 
> But you should try to get the source tags like so `const sourceTags = document.querySelectorAll(".lazy > source") and then attach the IntersectionObserver to this NodeList.
> 
> Have in mind that you should replace the img.src with the url in the data-src for browsers who don't support the IntersectionObserver with a simple check:
> 
> ```
> if (intersectionObserver in window) {
> ...
> } else {
> // replace img.src with data-src from img-tag or data-srcset from source-tag
> }
> ```
> 
> Hope, that helps.
> 
> Have a nice weekend.
> 
> M

Thank you so much for your help! 

I did a huge number of experiments, but could not implement the desired functionality. 

My goal is here (this is an implementation with a simple `img` tag): 

https://user-images.githubusercontent.com/30666874/144766029-5756ac93-c5c6-4914-87fa-d3860861df92.mp4

it's from here: https://bankist-pink.vercel.app/

Best seen in the third image: when the user reaches the image (200 pixels before the image), the intersectionObserver should trigger and call a function that should replace the low-resolution image with a high-resolution image. And when the user has scrolled to the image, the same observer should remove the class that implements the blur effect. 

I seem to have tried every possible way of assigning the "lazy-img" class to both the `<picture>` tag and the `<source>` tag, I also tried different options with assigning the observer to different nodes, but, all in vain. 

Maybe you can tell me what I'm doing wrong? 

Thanks to your awesome plugin and the image conversion mechanism built into parcel with the simple syntax "img.jpg?as=webp" and using the intersecionObserver API and the native ability of the <picture> tag to thicken the image format supported by the user browser, you can get a very convenient and reliable way of optimizing images without additional libraries. 

But I have no way to solve the puzzle of how to use the <picture> tag with the intersectionObserver API. 

Could it be that there is some conflict between your plugin and the intersectionObserver API? 

Thank you so much again for your help!

**Comment by haosmos** [comment]
> Hi! Please have in mind: the picture (or source) element itself does not display anything; it merely provides a context for its contained img element that enables it to choose from multiple URLs. That means, it is always the img element that will render the image that the user sees.
> 
> A normal usage would be like this:
> 
> ```
> <picture>
>   <source srcset="img/city-m.jpg" media="(max-width: 960px)">
>   <source srcset="img/city-l.jpg" media="(min-width: 961px)">
>   <img class="some-class" src="img/city-l.jpg" alt="city"/>
> </picture>
> ```
> 
> The lazy loading approach would look like this:
> 
> ```
> <picture class="lazy">
>   <source data-srcset="img/river-m.jpg" media="(max-width: 960px)">
>   <source data-srcset="img/river-l.jpg" media="(min-width: 961px)">
>   <img data-srcset="img/river-l.jpg" alt="river"/>
> </picture>
> ```
> 
> That means with JS you need to replace the data-srcset on the source element. The browser then takes this url and puts it into the img.src attribute.
> 
> In your code you're querying the img tags like so:
> 
> `const imgTargets = document.querySelectorAll("img[data-src]");``
> 
> But you should try to get the source tags like so `const sourceTags = document.querySelectorAll(".lazy > source") and then attach the IntersectionObserver to this NodeList.
> 
> Have in mind that you should replace the img.src with the url in the data-src for browsers who don't support the IntersectionObserver with a simple check:
> 
> ```
> if (intersectionObserver in window) {
> ...
> } else {
> // replace img.src with data-src from img-tag or data-srcset from source-tag
> }
> ```
> 
> Hope, that helps.
> 
> Have a nice weekend.
> 
> M

Thank you very much for your help! 

I was able to implement the desired functionality, but, not quite perfectly, maybe you can explain why? 

Here is what I got: 


https://user-images.githubusercontent.com/30666874/144939101-a5c7ab13-9fd1-470e-8918-64ebd7c36b75.mp4

It works the way I want it to, but implementing it exactly like using the `<img>` tag didn't work for some reason.

Here's what I have: 

1. image component markup: 

```
<picture>
	<source srcset="./img/digital-lazy.jpg?as=webp"
		type="image/webp"
		data-srcset="./img/digital.jpg?as=webp"
	/>

	<img src="./img/digital.jpg?as=webp"
		alt="Computer"
		class="features__img lazy-img"
	/>

</picture>
```

2. js code: 

```
// Lazy loading images
const imgTargets = document.querySelectorAll("picture > source");

const loadImg = function (entries, observer) {
  const [entry] = entries;

  if (!entry.isIntersecting) return;

  // Replace srcset with data-srcset
  entry.target.srcset = entry.target.dataset.srcset;

  entry.target.nextElementSibling.classList.remove("lazy-img");

  // entry.target.addEventListener("load", function () {
  //   console.log(`oho! the ${entry.target} was loaded!`);
  //   entry.target.classList.remove("lazy-img");
  // });

  observer.unobserve(entry.target);
};

const imgObserver = new IntersectionObserver(loadImg, {
  root: null,
  threshold: 0,
  rootMargin: "0px 0px -200px 0px",
});

imgTargets.forEach(picture => imgObserver.observe(picture));
```

Specifically, the problem is that for some reason this code does not work when the `<picture>` tag is used: 

```
entry.target.addEventListener("load", function () {
  entry.target.classList.remove("lazy-img");
});
```

although replacing the low-resolution image with a high-resolution image works: 

`entry.target.srcset = entry.target.dataset.srcset;`

That is, I want to wait for the high-resolution image to load and then remove the `lazy-img` class, which just adds the blur effect. 
That is, the problem is that this event:

```
entry.target.addEventListener("load", function () {
  entry.target.classList.remove("lazy-img");
});
```

doesn't work for some reason. So I use a workaround: 
 
`entry.target.nextElementSibling.classList.remove("lazy-img");`

And I don't wait for the high resolution picture to load. Though of course it would be correct to wait for the image to load, because the user might have network issues or some other problem. 

Although in the case of using the `<img>` tag the code: 

```
entry.target.addEventListener("load", function () {
  entry.target.classList.remove("lazy-img");
});
```

works. 

Maybe you know why the image loading event doesn't work? 

Once again, thank you very much for your comprehensive answers and for your wonderful plugin!
