### ISSUE TITLE
Not Working with posthtml-include

### ISSUE THREAD

**Issue by piyushwalia** [moritzlaube/parcel-transformer-html-datasrc#7]
Hi,

Trying to use lazy load with Parcel and followed all the instructions and its worked fine but when I use it in any posthml include file, it doesn't work. The output URL is the same when used under posthml include

Any help would be appreciated.

Thanks

**Comment by moritzlaube** [comment]
Hi! Can you provide a code example?

**Comment by mischnic** [comment]
I image the problem is that with `"*.html": ["parcel-transformer-html-datasrc", "..."]` this plugin runs before the included files are inlined, so it never actually sees the attributes in the included files. This parcelrc might work in that case:

```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{htm,html,xhtml}": [
      "@parcel/transformer-posthtml",
	  "parcel-transformer-html-datasrc",
      "@parcel/transformer-html"
    ]
  }
}
```

**Comment by piyushwalia** [comment]
Thank you for your prompt reply

My dependencies:-
```
 @parcel/transformer-sass": "^2.0.0",
    "include-media": "^1.4.10",
    "parcel": "^2.0.0",
    "parcel-transformer-html-datasrc": "^1.3.3",
    "posthtml-include": "^1.7.2"
```
.parcelrc
```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.html": ["parcel-transformer-html-datasrc", "..."]
  }
}
```

Code example:-

**This is working fine** 
Without using Posthtml-include
`<img data-src="/src/media/work/work_ecom-a-1.png"  class="lazy" alt="">`
_Output_
`<img data-src="/work_ecom-a-1.397084f1.png" class="lazy entered loaded" alt="" data-ll-status="loaded" src="/work_ecom-a-1.397084f1.png">`


**Doesnt output the URL - Not Working** 
Using data-src inside Posthtml-include
`<include src="filename.html"></include>`
and inside it, used the same image tag 
`<img data-src="/src/media/work/work_ecom-a-1.png"  class="lazy" alt="">`
_Output_
`<img data-src="/src/media/work/work_ecom-a-1.png" class="lazy entered error" alt="" data-ll-status="error" src="/src/media/work/work_ecom-a-1.png">`

**Comment by piyushwalia** [comment]
@mischnic,

Yes, Working fine now.

Thanks for the help. Really appreciate it.
